traveler/api/urls.py
from django.conf.urls import url, patterns
from traveler.models import Cast, Collection, LocastUser

api_index = [
    {
        'view': 'cast_api',
        'model': Cast
    },
    {
        'view': 'user_api',
        'model': LocastUser
    },
    {
        'view': 'collection_api',
        'model': Collection
    },
    {
        'description': u'Search',
        'view': 'search_api'
    },
    {
        'description': u'Geo features querying',
        'view': 'geofeatures_api'
    }
]

urlpatterns = patterns('traveler.api',
    # index
    url(r'^/?$', 'APIIndex', {'index': api_index}, name='api_index'),
)

urlpatterns += patterns('traveler.api.cast',
    # CAST
    url(r'^cast/(?P<cast_id>\d+)/media/(?P<media_id>\d+)/$', 'CastAPI', name='cast_media_api_single', kwargs={'method':'media_content'}),
    url(r'^cast/(?P<cast_id>\d+)/media/$', 'CastAPI', name='cast_media_api', kwargs={'method':'media'}),

    # comments
    url(r'^cast/(?P<cast_id>\d+)/comments/(?P<comment_id>\d+)/flag/$', 'CastAPI', name='cast_comments_api_single', kwargs={'method':'comments_flag'}),
    url(r'^cast/(?P<cast_id>\d+)/comments/(?P<comment_id>\d+)/$', 'CastAPI', name='cast_comments_api_single', kwargs={'method':'comments'}),
    url(r'^cast/(?P<cast_id>\d+)/comments/$', 'CastAPI', name='cast_comments_api', kwargs={'method':'comments'}),

    url(r'^cast/(?P<cast_id>\d+)/favorite/$', 'CastAPI', kwargs={'method':'favorite'}),
    url(r'^cast/(?P<cast_id>\d+)/flag/$', 'CastAPI', kwargs={'method':'flag'}),

    url(r'^cast/(?P<cast_id>\d+)/geofeature/$', 'CastAPI', kwargs={'method':'geofeature'}),

    url(r'^cast/(?P<cast_id>\d+)(?P<format>\.\w*)/$', 'CastAPI'),
    url(r'^cast/(?P<cast_id>\d+)/$', 'CastAPI', name='cast_api_single'),
    url(r'^cast/$', 'CastAPI', name='cast_api'),

    # casts in collections
    url(r'^collection/(?P<coll_id>\d+)/cast/(?P<cast_id>\d+)/$', 'CastAPI', name='collection_api_cast_single'),
    url(r'^collection/(?P<coll_id>\d+)/cast/$', 'CastAPI', name='collection_cast_api'),
)

# USER
urlpatterns += patterns('traveler.api.user',
    url(r'^user/(?P<user_id>\d+)/$', 'UserAPI', name='user_api_single'),
    url(r'^user/me/?$', 'UserAPI', kwargs={'method':'me'}),
    url(r'^user/$', 'UserAPI', name='user_api'),
)

urlpatterns += patterns('traveler.api.collection',
    # COLLECTION
    url(r'^collection/(?P<coll_id>\d+)/favorite/$', 'CollectionAPI', kwargs={'method':'favorite'}),

    url(r'^collection/(?P<coll_id>\d+)/$', 'CollectionAPI', name='collection_api_single'),
    url(r'^collection/$', 'CollectionAPI', name='collection_api'),
)


urlpatterns += patterns('traveler.api',
    # SEARCH
    url(r'^search/$', 'search.unified_search_api', name='search_api'),

    # get_features
    url(r'^geofeatures/$', 'geofeatures.get_geofeatures', name='geofeatures_api'),
)

traveler/urls.py
from django.conf.urls.defaults import patterns, url, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),
)

urlpatterns += patterns('traveler.views',
    url(r'^$', 'frontpage', name='frontpage'),
    url(r'^register/$', 'register', name='register'),
    url(r'^edit_profile/$', 'edit_profile', name='edit_profile'),
)

urlpatterns += patterns('traveler.views',
    url(r'^traveler.js', 'traveler_js', name='traveler_js'),
    url(r'^templates.js$', 'templates_js', name='templates_js'),
    url(r'^sync_code.png$', 'sync_code_png', name='sync_code_png'),
)

urlpatterns += patterns('locast.i18n.views',
    url(r'^setlang/$', 'set_language', name='set_language'),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
)

urlpatterns += patterns('locast.userconfirmation.views',
    url(r'^confirm_user/$', 'confirm_user', name='confirm_user'),
)

urlpatterns += patterns('',
    url(r'^api/', include('traveler.api.urls')),
)

urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings

urlpatterns = patterns('',
    url(r'^', include('traveler.urls')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}))

traveler/models.py
import cgi
import httplib
import settings
import urllib
import urlparse


from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.db.models.manager import GeoManager
from django.core.exceptions import ObjectDoesNotExist
from django.utils import simplejson, timezone
from django.utils.translation import ugettext_lazy as _

from locast.api import cache, datetostr
from locast.models import interfaces, modelbases, managers
from locast.models import ModelBase

from sorl.thumbnail import get_thumbnail
from sorl.thumbnail.helpers import ThumbnailError

def l_get_thumbnail(*args, **kwargs):
    import warnings
    try:
        return get_thumbnail(*args, **kwargs)
    except (IOError, ThumbnailError) as e:
        warnings.warn(e.message)
        return None

# DEPENDENCIES

class Tag(modelbases.Tag): pass

class Comment(modelbases.Comment,
        interfaces.Flaggable): 

    # TODO: this should be more generic incase anything else becomes commentable
    @models.permalink
    def get_api_uri(self):
        return ('cast_comments_api_single', [self.content_object.id, self.id])

    def get_absolute_url(self):
        return self.content_object.get_absolute_url()

class Flag(modelbases.Flag): pass

class UserActivity(modelbases.UserActivity): pass

class Boundary(modelbases.Boundary): pass

class MapPlace(modelbases.MapPlace): pass

# MAIN MODELS

class LocastUserManager(GeoManager, 
        managers.LocastUserManager): pass


class LocastUser(modelbases.LocastUser, 
        interfaces.Locatable):

    @models.permalink
    def get_api_uri(self):
        return ('user_api_single', [str(self.id)])

    def __unicode__(self):
        if self.email:
            return u'%s' % self.email
        else:
            return u'%s' % self.username

    def api_serialize(self, request):
        d = {'joined' : datetostr(self.date_joined)}
        profile = None
        try:
            profile = self.get_profile()
        except ObjectDoesNotExist:
            pass

        if ( profile ):
            d['profile'] = profile.api_serialize(request)

        return d


class LocastUserProfile(ModelBase):
    user = models.OneToOneField(LocastUser)

    user_image = models.ImageField(upload_to='user_images/%Y/%m/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    personal_url = models.URLField(null=True, blank=True)
    hometown = models.CharField(max_length=128, null=True, blank=True)

    @property
    def user_image_small(self):
        if self.user_image:
            return l_get_thumbnail(self.user_image, '150', quality=75)

    def api_serialize(self, request):
        d = {}
        if self.user_image:
            d['user_image'] = self.user_image.url
        
        if self.user_image_small:
            d['user_image_small'] = self.user_image_small.url

        if self.bio:
            d['bio'] = self.bio

        if self.personal_url:
            d['personal_url'] = self.personal_url

        if self.hometown:
            d['hometown'] = self.hometown

        return d


# A collection of casts
class Collection(ModelBase,
        interfaces.Authorable,
        interfaces.Titled,
        interfaces.Taggable, 
        interfaces.Favoritable):

    @models.permalink
    def get_api_uri(self):
        return ('collection_api_single', [str(self.id)])

    class Meta:
        verbose_name = _('collection')
        verbose_name_plural = _('collections')

    def __unicode__(self):
        return u'(id: %s) %s' % (str(self.id), self.title)

    def api_serialize(self, request):
        d = {}
        if self.path:
            d['path'] = self.path.coords
        d['casts'] = reverse('collection_cast_api', kwargs={'coll_id':self.id})

        d['casts_count'] = self.related_casts.count()

        if self.preview_image:
            d['preview_image'] = self.preview_image.url

        if self.thumbnail:
            d['thumbnail'] = self.thumbnail.url

        return d

    def geojson_properties(self, request):
        d = {}
        d['id'] = self.id
        d['title'] = self.title
        d['casts_count'] = self.related_casts.count()
        d['favorites'] = self.favorited_by.count()

        if self.preview_image:
            d['preview_image'] = self.preview_image.url

        if self.thumbnail:
            d['thumbnail'] = self.thumbnail.url

        return d

    objects = GeoManager() 

    related_casts = models.ManyToManyField('Cast', null=True, blank=True)
    
    path = gismodels.LineStringField(null=True,blank=True,srid=4326)  

    preview_image = models.ImageField(upload_to='content_images', null=True, blank=True)

    @property
    def thumbnail(self):
        return l_get_thumbnail(self.preview_image, '600', quality=75)


class Cast(ModelBase,
        interfaces.PrivatelyAuthorable, 
        interfaces.Titled, 
        interfaces.Commentable,
        interfaces.Favoritable,
        interfaces.Flaggable, 
        interfaces.Locatable, 
        interfaces.Taggable):

    @models.permalink
    def get_api_uri(self):
        return ('cast_api_single', [str(self.id)])

    def get_absolute_url(self):
        return reverse('frontpage') + '#!cast/' + str(self.id) + '/'

    class Meta:
        verbose_name = _('cast')

    def __unicode__(self):
        return u'%s (id: %s)' % (self.title, str(self.id))

    datetime = models.DateTimeField('Date and Time', default = timezone.now, null=True, blank=True)

    objects = GeoManager()

    def api_serialize(self, request):
        d = {}

        d['collections'] = []
        for i in self.collection_set.all():
            d['collections'].append(i.get_api_uri())

        if self.datetime:
            d['datetime'] = datetostr(self.datetime)

        d['media'] = reverse('cast_media_api', kwargs={'cast_id':self.id})
        d['comments'] = reverse('cast_comments_api', kwargs={'cast_id':self.id})

        if self.preview_image:
            d['preview_image'] = self.preview_image

        return d

    def geojson_properties(self, request):
        d = {}
        d['id'] = self.id
        d['title'] = self.title
        d['author'] = {'id' : self.author.id, 'display_name' : self.author.display_name }

        if self.datetime:
            d['datetime'] = datetostr(self.datetime)
        
        if self.preview_image:
            d['preview_image'] = self.preview_image

        if self.thumbnail:
            d['thumbnail'] = self.thumbnail.url

        d['favorites'] = self.favorited_by.count()

        return d

    # Returns the url of the preview image
    @property
    def preview_image(self):
        if len(self.imagemedia):
            image = self.imagemedia[0].content
            if image and image.file and image.medium_file:
                return image.medium_file.url

        elif len(self.videomedia):
            vid = self.videomedia[0].content
            if vid and vid.screenshot:
                return vid.screenshot.url

        elif len(self.linkedmedia):
            vid = self.linkedmedia[0].content
            if vid and vid.screenshot:
                return vid.screenshot

        return None

    @property
    def thumbnail(self):
        if self.preview_image:
            return l_get_thumbnail(self.preview_image, '150', quality=75)

        return None

    @property
    def videomedia(self):
        return self.media_set.filter(content_type_model='videomedia')

    @property
    def imagemedia(self):
        return self.media_set.filter(content_type_model='imagemedia')

    @property
    def linkedmedia(self):
        return self.media_set.filter(content_type_model='linkedmedia')

CAST_GEO_GROUP = 'cast_geo'

@receiver(signals.post_save, sender=Cast)
@receiver(signals.post_delete, sender=Cast)
def _clear_cast_geo_cache(sender, **kwargs):
    cache.incr_group(CAST_GEO_GROUP)


class Media(modelbases.LocastContent,
        interfaces.Authorable,
        interfaces.Locatable):

    @models.permalink
    def get_api_uri(self):
        return ('cast_media_api_single', [str(self.cast.id), str(self.id)])

    def api_serialize(self, request):
        d = {}
        d['language'] = self.language

        if self.caption:
            d['caption'] = self.caption

        if self.capture_time:
            d['capture_time'] = datetostr(self.capture_time)

        if self.cast:
            d['cast'] = self.cast.get_api_uri()

        return d 

    objects = GeoManager()

    # Caption length borrowed from pinterest.
    caption = models.CharField(max_length=500, null=True, blank=True)

    language = models.CharField(max_length=90,choices=settings.LANGUAGES, default='en')

    cast = models.ForeignKey(Cast, null=True, blank=True)
    
    capture_time = models.DateTimeField('date and time captured', null=True, blank=True)

    
class VideoMedia(Media, 
        modelbases.VideoContent):

    class Meta:
        verbose_name = _('video')

    def __unicode__(self):
        un = u'id: %s' % self.id
        if self.cast:
            un = un + u' (cast: %s)' % str(self.cast.id)

        return un

    def pre_save(self):
        if self.content_state == Media.STATE_INCOMPLETE:

            # If a file exists, that is good enough to be complete
            if self.file and self.file.size:
                self.content_state = Media.STATE_COMPLETE

    def process(self, force_update=False, verbose=False):

        # If the video is complete, start generating things.
        if self.content_state == Media.STATE_COMPLETE or force_update:
            self.content_state = Media.STATE_PROCESSING
            self.generate_screenshot(force_update=force_update, verbose=verbose)
            self.generate_web_stream(force_update=force_update, verbose=verbose)
            self.make_mobile_streamable()
            self.content_state = Media.STATE_FINISHED
            self.save()

traveler/templates/ajax/cast_frontpage.django.html
{% load i18n %}
{% load tz %}

<a href="#!" id="close-cast_{{cast.id}}" class="content-details-close locast-icon close"></a>

<div id="location-cast_{{cast.id}}" class="cast-location">{{cast.location.x}},{{cast.location.y}}</div>
<div class="indicator"></div>
<div id="casts" class="casts">
    <div id="open-cast_{{cast.id}}" class="locast-open-cast official-{{cast.author.is_staff|lower}} content-card cleared">
    
    <div class="cast-header">
    {% if cast.privacy == 3 %}
    <div class="cast-status">
        <h4><em>{% trans "Your Cast is Waiting to be Approved by a Moderator and is Not Visible to the Public" %}</em></h4>
    </div> 
    {% endif %}   
    {% if allowed_edit %}    
     <div class="delete-cast-prompt">
        <div class="delete-alert cleared">
            <h4>"{{cast.title}} " {% trans "Will Be Deleted! This Cannot be Undone!" %}</h4><br />
        <a href="#!" class="cancel locast-button">{% trans "Cancel"%}</a><a href="#!" class="delete locast-button">{% trans "Delete"%}</a>
        </div>
    </div>  
    {% endif %} 
    {% if allowed_edit %} 
        <div class="cast-edit-tools cleared secondary-color">
            <a href="#" class="delete-cast" id="delete-cast_{{cast.id}}">{% trans "Delete Cast" %}</a>   
            <a href="#" class="change-location" id="change-location-cast_{{cast.id}}">{% trans "Change Cast Location" %}</a>
        </div>
    {% endif %}
        <div id="actions-cast_{{cast.id}}" class="cast-actions secondary-color">
            <div id="favorite-cast_{{cast.id}}" class="favorite-cast {% if is_favorited %}favorited{% endif %}">
                <p>{% trans "favorite" %}</p>
                <a href="#" class="locast-icon large favorite grey action"></a> 
                 <div id="favorite-count-cast_{{cast.id}}" class="favorite-count">
                    {{ cast.favorited_by.count }}
                </div>
            </div>
            <div>
            {% if is_flagged %}
                <h6 class="flagged">{% trans "flagged" %}</h6>
            {% else %}
                <p>{% trans "flag" %}</p>
                <a id="flag-cast_{{cast.id}}" href="#" class="locast-icon large flag grey action"></a>
                <div id="flag-confirm-cast_{{cast.id}}" class="flag-confirm content-card"></div>
            {% endif %}
            </div>
        </div>
    <ul class="cast-collections cleared">
        {% for coll in cast.collection_set.all %}
            <li><a href="#!collection/{{coll.id}}/">{{coll.title}}</a></li>
        {% endfor %}
    </ul>

    <h3 class="cast-info" ><span class="title cast-title" >{{cast.title}}{% if allowed_edit %} <a class="edit-toggle locast-button" href="#!">{% trans "Edit Title" %}</a>{% endif %}
            </span>
          {% if allowed_edit %}
            <form id="title-form-cast_{{cast.id}}" class="cast-title-edit" method="post"> 
                <label for="id_title">{% trans "Edit Cast Title" %}</label>
                <input id="id_title" class="title-input" type="text" name="title" class="locast-textfield" value="{{cast.title}}" />
                <input type="submit" value="{% trans "update" %}" class="locast-button" />
            </form> 
            {% endif %}
            <br /><a href="#!user/{{cast.author.id}}/" class="author cast-author">{{cast.author.display_name}}</a></h3>
        <p class="cast-date date" title="{{cast.datetime|utc|date:"Y-m-d\TH:i:s\Z"}}">{{cast.datetime|utc|date:"Y-m-d\TH:i:s\Z"}}</p>
        
    </div>
    {% comment %}
    <div class="cast-sharing-tools locast-sharing-tools">        
    </div>
    {% endcomment %}
    <div class="cast-content">
        <div class="content cast-media">
        {% if not cast.imagemedia and not cast.linkedmedia and not cast.videomedia %}
            <h5 class="locast-instruction secondary-color" id="no-media-message">there are no media </h5>
        {% else %}
            <a id="media-last" class="media-nav secondary-color"> &lsaquo; </a> <a id="media-next" class="media-nav secondary-color"> &rsaquo; </a>
            <h4 id="cast-media-count" class="secondary-color">
                <span id="current-media"> 1 </span> {% trans "of" %} <span id="total-media"> 1 </span></p> 
            </h4> 
        {% endif %}
        {% if allowed_edit %}
            <a class="locast-button" id="add-media-button-cast_{{cast.id}}">{% trans "+ add media" %}</a>
        {% endif %}
            <ul class="media-list" id="media-list-cast_{{cast.id}}">
            {% for v in cast.videomedia %}{% if v.content.file %}
                {% if v.content.web_stream_file %}
                    <li class="video cleared">
                    {% if allowed_edit %}
                        <a id="delete-media_{{v.content.id}}" class="delete-media secondary-color">delete</a>
                    {% endif %}
                        <a class="web-stream-file" data-video-file="{{v.content.file.url}}" data-video-screenshot="{{v.content.screenshot.url}}">
                            <div class="image-frame">
                            {% if v.content.caption %}
                                <h6 class="title">{{v.content.caption}}</h6>
                            {% endif %}
                                <div class="video-icon"></div>
                                <img src="{{v.content.screenshot.url}}"></img>
                            </div>
                        </a>
                    </li>
                {% else %}
                    <li class="video cleared">
                        <div class="image-frame no-media">
                            <h6 class="title">{% if v.content.caption %}"{{v.content.caption}}" {% endif %}{% trans "Video is Processing" %}</h6>
                        </div>
                    </li>
                {% endif %}
            {% endif %}{% endfor %}

            {% for l in cast.linkedmedia %}{% if l.content.screenshot %}
                <li class="linked-video cleared">
                {% if allowed_edit %}
                    <a id="delete-media_{{l.content.id}}" class="delete-media secondary-color">delete</a>
                {% endif %}
                    <a class="{{l.content.content_provider|cut:'.'}}" href="{{l.content.url}}">
                        <div class="image-frame">
                        {% if l.content.caption %}
                            <h6 class="title">{{l.content.caption}}</h6>
                        {% endif %}
                        <div class="video-icon"></div>
                        <img src="{{ l.content.screenshot }}"></img>
                        </div>
                    </a>                
                </li>
            {% endif %}{% endfor %} 

            {% for i in cast.imagemedia %}{% if i.content.file %}
                <li class="photo cleared">
                {% if allowed_edit %}
                    <a id="delete-media_{{i.content.id}}" class="delete-media secondary-color">delete</a>
                {% endif %}
                <a class="cast-photo" href="{{i.content.file.url}}" rel="media" title="{% if i.content.caption %}<h4> {{i.content.caption}} </h4>{% endif %}">
                        <div class="image-frame">
                            {% if i.content.caption %}<h6 class="title">{{i.content.caption}}</h6>{% endif %}
                            <img src="{{i.content.medium_file.url}}" />
                        </div>
                    </a> 
                </li>
            {% endif %}{% endfor %}
            </ul> 
        </div>

        <div class="content cast-description">
            <ul id="tag-list-cast_{{cast.id}}" class="cast-tags cleared">
            {% for tag in cast.visible_tags.all %}
            <li><a href="#!tag/{{tag}}/" class="cast-tag">{{tag}}</a>{% if allowed_edit %}<a title="delete this tag" class="delete-tag">[X]</a>{% endif %}</li>
            {% endfor %}
            {% if allowed_edit %}<br /><a class="edit-toggle locast-button">{% trans "Add Tags" %}</a> {% endif %}
            </ul>
            {% if allowed_edit %}
            <form id="tag-form-cast_{{cast.id}}" class="tag-edit" method="post"> 
                <label for="id_tags">{% trans "Add Tags" %}</label>
                <input id="id_tags" autocomplete="off" type="text" maxlength="200" name="tags" class="locast-textfield">
                <p class="locast-help">{% trans "seperate tags with a comma" %}</p>
                <input type="submit" value="add tags" class="locast-button" />
            </form>
            {% endif %}

            <div class="description" id="description-cast_{{cast.id}}">
                <p>{% if cast.description %}{{cast.description|linebreaksbr}}{% endif %}</p>
            {% if allowed_edit %}
            <br /><a class="edit-toggle locast-button">{% trans "Edit Description" %}</a>
            {% endif %}
            </div>
            {% if allowed_edit %}
                <form id="description-form-cast_{{cast.id}}" class="cast-description-edit" method="post"> 
                <label for="id_description">{% trans "Edit Description" %}</label>
                <textarea id="id_description" type="text" name="description" class="locast-textfield">{% if cast.description %}{{cast.description}}{% endif %}</textarea>
                <input type="submit" value="{% trans "update" %}" class="locast-button" />
            </form> 
            {% endif %}
                </div>

        <div class="cast-comments closed content">
            <!--<a id="comments-minimize" href="#!">{% trans "Show Comments"%}</a>-->
            <div class="comments">
            <h4 class="sub-title">{% trans "Comments" %}</h4>
            <div id="comments-cast_{{cast.id}}"></div>
            {% if request.user.is_authenticated %}
            <form id="content-form-cast_{{cast.id}}">
                <textarea id="id_content" name="content" cols="10" rows="2" class="locast-textfield"></textarea>
                <input type="submit" value="post Comment" class="locast-button" />   
            </form>    
            {% else %}
            <a href="{{FULL_BASE_URL}}/login" class="locast-button">{% trans 'Login to comment!' %}</a>
            {% endif %}
        </div>
    </div>

    {% if allowed_edit %}
    <div id="add-media-cast_{{cast.id}}" class="add-media-cast content-card">
        <a class="locast-icon locast-button close" id="add-media-close-cast_{{cast.id}}" >{% trans 'Cancel'%}</a>
        <h4>{% trans "Add Photo to Cast" %}</h4>
        <form id="photo-upload-form-cast_{{cast.id}}" method="post">
            <div id="photo-uploader-cast_{{cast.id}}" class="locast-upload-box">
                <a href="#" id="photo-uploader-cast_{{cast.id}}-chooser" >{% trans "+ Add A Photo" %}</a>
                <div id="photo-uploader-cast_{{cast.id}}-list"></div>
            </div>
            <div class="upload-info hidden">
                <label for="id_caption">{% trans "caption (optional)" %}</label>
                <input id="id_caption" type="text" value="" maxlength="160" name="caption" class="locast-textfield">
                <input type="hidden" name="content_type" value="imagemedia"></input>
                <input type="submit" value="Upload" class="locast-button" />
            </div>
        </form>

        <h4>{% trans "Add Video to Cast" %}</h4>
        <form id="video-upload-form-cast_{{cast.id}}" method="post">
            <div id="video-uploader-cast_{{cast.id}}" class="locast-upload-box">
                <a href="#" id="video-uploader-cast_{{cast.id}}-chooser"  title="select file">{% trans "+ Add A Video" %}</a>
                <div id="video-uploader-cast_{{cast.id}}-list"></div> 
            </div>
            <div class="upload-info hidden">
                <label for="id_caption">{% trans "caption (optional)" %}</label>
                <input id="id_caption" type="text" value="" maxlength="160" name="caption" class="locast-textfield">
                <input type="hidden" name="content_type" value="videomedia"></input>

                <input type="submit" value="Upload" class="locast-button" />
            </div>  
        </form>

        <form id="link-post-form-cast_{{cast.id}}" method="post"> 
            <h4><label for="id_url">{% trans "Link Video to Cast" %}</label></h4>
            <input id="id_url" type="text" maxlength="200" name="url" class="locast-textfield">
            <p class="locast-help">{% trans 'enter link to a <a href="http://youtube.com" target="new">YouTube</a> or <a href="http://vimeo.com" target="new" >Vimeo</a> video' %}</p>
            <input type="hidden" name="content_type" value="linkedmedia"></input>
            <input type="submit" value="post link" class="locast-button" />
        </form>
    </div>
    
    <div class="delete-media-prompt">
        <div class="delete-alert cleared">
        <h4>{% trans "This Media Will Be Deleted" %}</h4>
        <a href="#!" class="cancel locast-button">{% trans "Cancel"%}</a><a href="#!" class="delete locast-button">{% trans "Delete"%}</a>
        </div>
    </div> 
   
    {% endif %}
</div>    
</div>
</div>